export { HomePage } from "./Home/HomePage"
export { ProductDetailsPage } from "./ProductDetails/ProductDetailsPage"
export { DashboardPage } from "./Dashboard/DashboardPage"
export { ProductsPage } from "./Products/ProductsPage"
export { RegisterPage } from "./Register/RegisterPage"
export { LoginPage } from "./Login/LoginPage"
